### PR TITLE
Support horizontal scroll/pan + more mouse buttons

### PR DESCRIPTION
**Pull request by antonok-edm**
I added support for horizontal scrolling (also known as pan) in the default `MouseReport`.

I also increased the maximum number of supported buttons to 8 - this still fits in a byte and enables Back/Forward and additional app-specific buttons.

### CODE REVIEW

**Comment by twitchyliquid64** [comment]
Thanks! Did you get the chance to test it on any platforms? In particular im interested if windows considers this a valid pointer device (given it deviates from the standard 'mouse' descriptor in the spec)

**Comment by antonok-edm** [comment]
I've been developing it to work with a Linux host, and since you mentioned it I've just confirmed that it works on a Windows machine as well.

**Comment by haata** [comment]
Is there a particular reason to use PAN instead of AC_PAN as it's called in the HID Spec?

**Comment by antonok-edm** [comment]
Nope, that's a good point - fixed!

**Pull request merged**
